if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    get_property(isMultiConfig GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
    set(INFO_DIR info)
    if (isMultiConfig)
        list(APPEND CMAKE_CONFIGURATION_TYPES "WithoutDebInfo")

        foreach (buildType IN LISTS CMAKE_CONFIGURATION_TYPES)
            file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/${buildType}/${INFO_DIR})
        endforeach ()
    else ()
        file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/${INFO_DIR})
        set(allowedBuildTypes Debug Release RelWithDebInfo)
        set_property(CACHE CMAKE_BUILD_TYPE PROPERTY
            STRINGS "${allowedBuildTypes}"
        )
        if (NOT CMAKE_BUILD_TYPE)
            set(CMAKE_BUILD_TYPE Debug CACHE STRING "" FORCE)
        elseif (NOT CMAKE_BUILD_TYPE IN_LIST allowedBuildTypes)
            message(FATAL_ERROR "Unknown build type: ${CMAKE_BUILD_TYPE}")
        endif ()
    endif ()

    set(CMAKE_C_FLAGS_DEBUG "-g -O0")
    set(CMAKE_CXX_FLAGS_DEBUG "-g -O0")
    if (isMultiConfig)
        set(CMAKE_EXE_LINKER_FLAGS_DEBUG "-g -O0 -Wl,-Map=${CMAKE_BINARY_DIR}/Debug/info/main.map")
    else ()
        set(CMAKE_EXE_LINKER_FLAGS_DEBUG "-g -O0 -Wl,-Map=${CMAKE_BINARY_DIR}/info/main.map")
    endif ()
    set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "-g -O0")
    set(CMAKE_STATIC_LINKER_FLAGS_DEBUG "")
    set(CMAKE_MODULE_LINKER_FLAGS_DEBUG "-g -O0")

    set(CMAKE_C_FLAGS_RELEASE "-O3")
    set(CMAKE_CXX_FLAGS_RELEASE "-O3")
    if (isMultiConfig)
        set(CMAKE_EXE_LINKER_FLAGS_RELEASE "-O3 -Wl,-Map=${CMAKE_BINARY_DIR}/Release/info/main.map")
    else ()
        set(CMAKE_EXE_LINKER_FLAGS_RELEASE "-O3 -Wl,-Map=${CMAKE_BINARY_DIR}/info/main.map")
    endif ()
    set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "-O3")
    set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "")
    set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "-O3")

    set(CMAKE_C_FLAGS_RELWITHDEBINFO "-g -O3")
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-g -O3")
    if (isMultiConfig)
        set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "-g -O3 -Wl,-Map=${CMAKE_BINARY_DIR}/RelWithDebInfo/info/main.map")
    else ()
        set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "-g -O3 -Wl,-Map=${CMAKE_BINARY_DIR}/info/main.map")
    endif ()
    set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "-g -O3")
    set(CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO "")
    set(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO "-g -O3")

    set(CMAKE_C_FLAGS_WITHOUTDEBINFO "-O0")
    set(CMAKE_CXX_FLAGS_WITHOUTDEBINFO "-O0")
    if (isMultiConfig)
        set(CMAKE_EXE_LINKER_FLAGS_WITHOUTDEBINFO "-O0 -Wl,-Map=${CMAKE_BINARY_DIR}/RelWithDebInfo/info/main.map")
    else ()
        set(CMAKE_EXE_LINKER_FLAGS_WITHOUTDEBINFO "-O0 -Wl,-Map=${CMAKE_BINARY_DIR}/info/main.map")
    endif ()
    set(CMAKE_SHARED_LINKER_FLAGS_WITHOUTDEBINFO "-O0")
    set(CMAKE_STATIC_LINKER_FLAGS_WITHOUTDEBINFO "")
    set(CMAKE_MODULE_LINKER_FLAGS_WITHOUTDEBINFO "-O0")
endif()

